[package]
name = "stabilizer"
version = "0.1.0"
authors = ["Robert Jördens <rj@quartiq.de>"]
description = "Firmware for the Sinara Stabilizer board (stm32h743, eth, poe, 2 adc, 2 dac)"
categories = ["embedded", "no-std", "hardware-support", "science"]
license = "GPL-3.0-or-later"
keywords = ["ethernet", "eth", "stm32", "stm32h7", "adc", "dac", "tcp", "no-std", "embedded"]
repository = "https://github.com/quartiq/stabilizer"
readme = "README.md"
#documentation = "https://docs.rs/stabilizer/"
edition = "2018"
publish = false
exclude = [
	".travis.yml",
	".gitignore",
	"doc/",
	"doc/*"
]

[badges]
travis-ci = { repository = "quartiq/stabilizer", branch = "master" }
maintenance = { status = "experimental" }

[package.metadata.docs.rs]
features = []
default-target = "thumbv7em-none-eabihf"

[dependencies]
cortex-m = { version = "0.5", features = ["inline-asm", "const-fn"] }
cortex-m-rt = { version = "0.6", features = ["device"] }
cortex-m-log = { version = "0.4", features = ["log-integration"] }
stm32h7 = { version = "0.6", features = ["stm32h7x3", "rt"] }
# stm32h7 = { path = "../stm32-rs/stm32h7", features = ["stm32h7x3", "rt"] }
log = "0.4"
panic-abort = "0.3"
panic-semihosting = { version = "0.5", optional = true }
smoltcp = { version = "0.5.0", default-features = false, features = ["proto-ipv4", "socket-tcp", "log"] }

[features]
semihosting = ["panic-semihosting", "cortex-m-log/semihosting"]
bkpt = [ ]

[build-dependencies]
built = "0.3"

[profile.dev]
codegen-units = 1
incremental = false

[profile.release]
debug = true
lto = true
codegen-units = 1
