[package]
name = "stabilizer"
version = "0.1.0"
authors = ["Robert Jördens <rj@quartiq.de>"]
categories = ["embedded", "no-std"]
license = "GPL-3"
keywords = ["ethernet", "eth", "stm32", "adc", "dac", "tcp"]
repository = "https://github.com/quartiq/stabilizer"
#documentation = "https://docs.rs/stabilizer/"
edition = "2018"

[badges]
travis-ci = { repository = "jordens/stabilizer", branch = "master" }
maintenance = { status = "experimental" }

[package.metadata.docs.rs]
features = []
default-target = "thumbv7em-none-eabihf"

[dependencies]
cortex-m = { version = "0.5" }
cortex-m-rt = { version = "0.6", features = ["device"] }
cortex-m-log = { version = "0.4", features = ["log-integration"] }
stm32h7 = { version = "0.6", features = ["stm32h7x3", "rt"] }
embedded-hal = "0.2"
log = "0.4"
panic-abort = "0.3"
panic-semihosting = { version = "0.5", optional = true }
smoltcp = { version = "0.5.0", default-features = false, features = ["proto-ipv4", "socket-tcp", "log"] }

[features]
semihosting = ["panic-semihosting", "cortex-m-log/semihosting"]

[build-dependencies]
built = "0.3"

[profile.dev]
codegen-units = 1
incremental = false

[profile.release]
debug = true
lto = true
codegen-units = 1
incremental = false
opt-level = 2
